<?php /** @var $block \Byjuno\ByjunoCore\Block\Threatmetrix */ ?>
<?php if ($block->isAvailable()): ?>
    <script type="text/javascript" src="https://h.online-metrix.net/fp/tags.js?org_id=<?php echo $block->getOrgId(); ?>&session_id=<?php echo $block->getSessionId(); ?>&pageid=checkout"></script>
    <noscript>
        <iframe style="width: 100px; height: 100px; border: 0; position: absolute; top: -5000px;" src="https://h.online-metrix.net/tags?org_id=<?php echo $block->getOrgId(); ?>&session_id=<?php echo $block->getSessionId(); ?>&pageid=checkout"></iframe>
    </noscript>
<?php endif; ?>