<?php /** @var $block \Byjuno\ByjunoCore\Block\Threatmetrix */ ?>
<?php if ($block->isAvailable()): ?>
    <script>
        window.addEventListener('load', function () {
            window.setTimeout(function() {
                const s = document.createElement('script');
                s.type = 'text/javascript';
                s.src = 'https://h.online-metrix.net/fp/tags.js?org_id=<?php echo $block->getOrgId(); ?>&session_id=<?php echo $block->getSessionId(); ?>&pageid=checkout';
                s.async = true;
                document.body.appendChild(s);
            }, 0);
        });
    </script>
    <link rel="preload" href="https://h.online-metrix.net/fp/tags.js?org_id=<?php echo $block->getOrgId(); ?>&session_id=<?php echo $block->getSessionId(); ?>&pageid=checkout" as="script">
    <noscript>
        <iframe style="width: 100px; height: 100px; border: 0; position: absolute; top: -5000px;" src="https://h.online-metrix.net/tags?org_id=<?php echo $block->getOrgId(); ?>&session_id=<?php echo $block->getSessionId(); ?>&pageid=checkout"></iframe>
    </noscript>
<?php endif; ?>
