<?php $_htmlId = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass = $this->getElement()->getClass() ?>
<?php $_htmlName = $this->getElement()->getName() ?>

<tr>

    <td colspan="11" class="grid tier">
        <input id="ice_webservice" type="hidden" name="groups[iceadvanced][fields][webservice_data][value]" value="0"/>
        <table class="icepaypaymentmethods" id="modules_table" style="width:100%;">
            <thead>
                <tr class="headings">
                    <th>Paymentmethod</th>
                    <th>Title</th>
                    <th>Issuers</th>
                    <th>Settings</th>
                    <th>Active</th>
                </tr>
            </thead>
            <tbody id="<?php echo $_htmlId ?>_container"></tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
                </tr>
            </tfoot>
        </table>

        <script type="text/javascript" src="<?php echo $this->getJS('tiny_mce/tiny_mce.js'); ?>"></script>
        <script type="text/javascript">
            //<![CDATA[

            var ICEPAYPaymentMethodRowTemplate = '<tr id="icepay_{{index}}">'
                    + '<td>{{pm_img}}</td>'
                    + '<td><input class=" required-entry validate-length minimum-length-5 maximum-length-32 input-text" type="text" name="groups[{{module_namespace}}][fields][{{pm_key}}title][value]" value="{{pm_title}}" id="icepay_module_row_{{index}}_serial" style="width:93px;"/></td>'
                    + '<td>{{pm_issuers}}</td>'
                    + '<td><button type="button" class="scalable " onclick="icepayEditor.open(\'<?php echo $this->_ajaxLoadPaymentMethodURL ?>\', \'icepay_module_row_{{index}}_serial\')" style=""><span>Configure</span></button></td>'
                    + '<td><select class="<?php echo $_htmlClass ?>" name="groups[{{module_namespace}}][fields][{{pm_key}}active][value]" id="icepay_pm_row_{{index}}_enabled" {{module_active_switch}}>'
                    + '<option value="1">Enabled</option>'
                    + '<option value="0">Disabled</option>'
                    + '</select></td>'
                    + '</tr>';

            var ICEPAYRetrievedPaymentMethodRowTemplate = '<tr id="icepay_{{index}}">'
                    + '<input type="hidden" name="groups[{{module_namespace}}][fields][{{pm_key}}_][value]" id="icepay_pm_row_{{index}}_issuerdata" value="{{pm_issuerdata}}"/>'
                    + '<input type="hidden" name="groups[{{module_namespace}}][fields][{{pm_key}}issuer][value]" id="icepay_pm_row_{{index}}_issuerdata" value="{{pm_issuerdata}}"/>'
                    + '<td>{{pm_img}}</td>'
                    + '<td><input class=" required-entry validate-length minimum-length-5 maximum-length-32 input-text" type="text" name="groups[{{module_namespace}}][fields][{{pm_key}}title][value]" value="{{pm_title}}" id="icepay_module_row_{{index}}_serial" style="width:93px;"/></td>'
                    + '<td>{{pm_issuers}}</td>'
                    + '<td>Save Config to configure</td>'
                    + '<td><select class="<?php echo $_htmlClass ?>" name="groups[{{module_namespace}}][fields][{{pm_key}}active][value]" id="icepay_pm_row_{{index}}_enabled" {{module_active_switch}}>'
                    + '<option value="1">Enabled</option>'
                    + '<option value="0">Disabled</option>'
                    + '</select></td>'
                    + '</tr>';

            var ICEPAYSettingsTemplate = '<p id="{{msg_id}}" class="{{type}}">{{msg}}</p>';


            var ICEPAY = {
                template: new Template(ICEPAYPaymentMethodRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
                ajaxTemplate: new Template(ICEPAYRetrievedPaymentMethodRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
                msgTemplate: new Template(ICEPAYSettingsTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
                itemsCount: 0,
                msgCount: 0,
                addItem: function() {
                    var data = {
                        pm_code: '',
                        pm_title: '',
                        pm_active: '',
                        pm_key: '',
                        pm_info: '',
                        pm_img: '',
                        pm_issuers: '',
                        pm_issuerdata: '',
                        pm_issuerimage: '',
                        module_namespace: '',
                        module_template: '',
                        index: this.itemsCount++
                    };

                    data.pm_code = arguments[0];
                    data.pm_title = arguments[1];
                    data.pm_img = arguments[2];
                    data.pm_issuers = arguments[3];
                    data.pm_active = arguments[4];
                    data.pm_info = arguments[5];
                    data.pm_issuerdata = arguments[6];
                    data.module_template = (arguments[7]) ? 1 : 0;

                    data.pm_key = 'pm_' + arguments[0].toLowerCase() + '_';
                    data.module_namespace = 'paymentmethod';

                    Element.insert($('<?php echo $_htmlId ?>_container'), {
                        bottom: (data.pm_issuerdata) ? this.ajaxTemplate.evaluate(data) : this.template.evaluate(data)
                    });

                    $('icepay_pm_row_' + data.index + '_enabled').selectedIndex = (data.pm_active == "1") ? 0 : 1;
                },
                addMessage: function() {

                    var data = {
                        type: '',
                        msg: '',
                        msg_id: '',
                        index: this.msgCount++
                    };


                    data.type = arguments[0];
                    data.msg = arguments[1];
                    data.msg_id = "msg_id_" + data.index.toString();

                    Element.insert($('icepay_debugger'), {
                        bottom: this.msgTemplate.evaluate(data)
                    });

                },
                clearMessages: function() {
                    for (var i = 0; i < this.msgCount; i++) {
                        try {
                            Element.remove($('msg_id_' + i.toString()));
                        } catch (err) {
                            alert(err.toString());
                        }
                    }
                    this.msgCount = 0;
                },
                clearAll: function() {
                    for (var i = 0; i < this.itemsCount; i++) {
                        try {
                            Element.remove($('icepay_' + i));
                        } catch (err) {
                        }
                    }
                    this.itemsCount = 0;
                },
                retrieveFromICEPAY: function() {
                    var url = '<?php echo $this->_ajaxGetPaymentMethodsURL ?>';
                    var parameters = {};
                    new Ajax.Request(url, {
                        parameters: parameters,
                        onComplete: function(response) {
                            if (response.status === 200) {
                                var result = response.responseText.evalJSON();

                                if (result.msg) {
                                    ICEPAY.clearMessages();
                                    for (var i = 0; i < result.msg.length; i++)
                                        ICEPAY.addMessage(result.msg[i].type, result.msg[i].msg);
                                }

                                if (result.paymentmethods) {
                                    ICEPAY.clearAll();
                                    $('ice_webservice').value = 1;

                                    for (var i = 0; i < result.paymentmethods.length; i++) {
                                        var issuers = (result.paymentmethods[i].Issuers.Issuer.length > 0) ? result.paymentmethods[i].Issuers.Issuer.length.toString() + " issuers" : "1 issuer";

                                        ICEPAY.addItem(
                                                result.paymentmethods[i].PaymentMethodCode,
                                                result.paymentmethods[i].Description,
                                                result.paymentmethods[i].Image,
                                                issuers,
                                                result.paymentmethods[i].ConfigActive,
                                                result.paymentmethods[i].ConfigDescription,
                                                result.issuers[i]["data"]);
                                    }
                                }
                            }
                        },
                        onError: function(response) {

                        }
                    });
                    return true;
                }
            };


<?php foreach ($this->getPaymentmethods() as $_item): ?>
    <?php if (intval($_item['issuers']) > 0): ?>
                    ICEPAY.addItem(
                            '<?php echo $_item['code'] ?>',
                            '<?php echo $_item['name'] ?>',
                            '<?php echo $_item['image'] ?>',
                            '<?php echo $_item['issuers'] ?>',
                            '<?php echo $_item['active'] ?>',
                            '<?php echo $_item['info'] ?>',
                            null
                            );
    <?php endif; ?>
<?php endforeach; ?>


            var url = '<?php echo $this->_ajaxSavePaymentMethodURL ?>';
            var parameters = {};

            var icepayEditor = {
                overlayShowEffectOptions: null,
                overlayHideEffectOptions: null,
                open: function(editorUrl, elementId) {
                    if (editorUrl && elementId) {
                        new Ajax.Request(editorUrl, {
                            parameters: {
                                element_id: '', //elementId+'_editor',
                                store_id: '0'
                            },
                            onSuccess: function(transport) {
                                try {
                                    this.openDialogWindow(transport.responseText, elementId);
                                } catch (e) {
                                    alert(e.message);
                                }
                            }.bind(this)
                        });
                    }
                },
                openDialogWindow: function(content, elementId) {
                    this.overlayShowEffectOptions = Windows.overlayShowEffectOptions;
                    this.overlayHideEffectOptions = Windows.overlayHideEffectOptions;
                    Windows.overlayShowEffectOptions = {duration: 0};
                    Windows.overlayHideEffectOptions = {duration: 0};

                    Dialog.confirm(content, {
                        draggable: true,
                        resizable: true,
                        closable: true,
                        className: "magento",
                        windowClassName: "popup-window",
                        title: 'ICEPAY paymentmethod configuration',
                        width: 750,
                        height: 555,
                        zIndex: 1000,
                        recenterAuto: false,
                        hideEffect: Element.hide,
                        showEffect: Element.show,
                        id: "catalog-wysiwyg-editor",
                        buttonClass: "form-button",
                        okLabel: "Save settings",
                        cancelLabel: "Cancel",
                        ok: this.saveDialogWindow.bind(this),
                        cancel: this.closeDialogWindow.bind(this),
                        onClose: this.closeDialogWindow.bind(this),
                        firedElementId: elementId
                    });

                    content.evalScripts.bind(content).defer();

                },
                saveDialogWindow: function(dialogWindow) {

                    var parameters = $('icepay_paymentmethod').serialize(true);
                    parameters.active_issuers = $('iceadvanced_generic_issuers').getValue().join(',');
                    parameters.specificcountry = $('iceadvanced_generic_specificcountry').getValue().join(',');
                    dialogWindow.hide();

                    new Ajax.Request(url, {
                        parameters: parameters,
                        onComplete: function(response) {
                            if (response.status == 200) {

                            }
                        },
                        onError: function(response) {
                            alert("error");
                        },
                        onSuccess: function(transport) {
                            alert(transport.responseText);
                        }

                    });
                    this.closeDialogWindow(dialogWindow);

                },
                okDialogWindow: function(dialogWindow) {
                    if (dialogWindow.options.firedElementId) {
                        wysiwygObj = eval('wysiwyg' + dialogWindow.options.firedElementId + '_editor');
                        wysiwygObj.turnOff();
                        if (tinyMCE.get(wysiwygObj.id)) {
                            $(dialogWindow.options.firedElementId).value = tinyMCE.get(wysiwygObj.id).getContent();
                        } else {
                            if ($(dialogWindow.options.firedElementId + '_editor')) {
                                $(dialogWindow.options.firedElementId).value = $(dialogWindow.options.firedElementId + '_editor').value;
                            }
                        }
                    }
                    this.closeDialogWindow(dialogWindow);
                },
                closeDialogWindow: function(dialogWindow) {
                    dialogWindow.close();
                    Windows.overlayShowEffectOptions = this.overlayShowEffectOptions;
                    Windows.overlayHideEffectOptions = this.overlayHideEffectOptions;
                }
            };

            //]]>
        </script>
    </td></tr>